###############################################################
# Project:    EU Tweet
# Task:       Visual descriptive overview of EU Tweet Sample
#             against benchmark sample
# Author:     Christian Rauh (31.05.2021)
##############################################################

# Packages ####
library(tidyverse) # 1.3.0
library(patchwork) # 1.1.1
library(ggridges) # 0.5.2
library(ggtext) # 0.1.1
library(scales) # 1.1.1



# The data ####

# As generated by 3_AnalyticDataSet.R and preceeding steps
tweets <- read_rds("./data/AnalyticData_AllSamples.RDS")

# Sample for testing purpose
# tweets <- tweets %>% sample_n(10000)

# Correct some coding nuissances
# Probably corect downstream!
tweets$nexturl[is.na(tweets$nexturl)] <- 0 # there were just none
tweets$nphotos[is.na(tweets$nphotos)] <- 0 # there were just none
tweets$nvideos[is.na(tweets$nvideos)] <- 0 # there were just none
tweets$ntube[is.na(tweets$ntube)] <- 0 # there were just none
tweets$lsd[!tweets$en_av] <- NA # If there was no english text, sentiment score is missing, not 0

# Mark original (self-authored) tweets
# excluding retweets and quotes
tweets$original <- tweets$is_retweet == F & tweets$is_quote == F
sum(tweets$original)

# Mark benchmark samples for plotting
tweets$benchmark <- !str_detect(tweets$tweetsample, "EU ")

# Nicer group names for plotting
tweets$group <- tweets$tweetsample
tweets$group[tweets$group == "EU (inst. account)"] <- "EU supranational\n(institutional accounts)"
tweets$group[tweets$group == "EU (pers. account)"] <- "EU supranational\n(personal accounts)"
tweets$group[tweets$group == "IO"] <- "International Organisations\n(institutional accounts)"
tweets$group[tweets$group == "UK"] <- "UK government accounts"
tweets$group[tweets$group == "TWT"] <- "Random Tweets"
tweets$group <- factor(tweets$group, 
                       levels = c("Random Tweets",
                                  "UK government accounts",
                                  "International Organisations\n(institutional accounts)",
                                  "EU supranational\n(personal accounts)",
                                  "EU supranational\n(institutional accounts)"))


# Time markers
tweets$month <- str_extract(as.character(tweets$day), "[0-9]{4}-[0-9]{2}")


# Overarching ggplot params ####

theme_set(theme_light() +
            theme(legend.position = "none",
                  axis.text = element_text(color = "black"),
                  plot.title = element_text(size=10),
                  panel.grid.minor = element_blank()))

benchmarkcolors <- c("#003399", "#FFCC00") # EU, all the way down ...
benchmarkshapes <- c(18, 19)



# Tweet output ####

# Monthly number of supranational tweets # 
eumonthly <- tweets %>% 
  filter(!benchmark) %>% # Only the EU Tweets
  group_by(month) %>% 
  summarise(count = n()) %>% 
  arrange(month)

# Ensure full range of months
months <- seq.Date(from = min(tweets$day[!tweets$benchmark]), 
                   to = max(tweets$day[!tweets$benchmark]), 
                   by = "days") %>% 
  as.character() %>% 
  str_remove("-[0-9]{2}$") %>% 
  unique() %>% 
  as.data.frame() %>% 
  rename(month = 1)

# Plotting markers
t.breaks <- months %>% 
  filter(str_detect(month, "-01")) # Only Januaries
t.breaks <- t.breaks[,1] # Atomic vector
t.labels <- str_remove(t.breaks, "-01")  

# Join series
eumonthly <- left_join(months, eumonthly, by = "month")

# Plot time series
pl.output.month <- 
  ggplot(eumonthly, aes(x=month, y = count, group = 1))+
  geom_bar(stat = "identity", width = .5, fill = "#003399", color = "#003399")+
  # geom_line()+
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  labs(title = "Number of tweets by supranational EU actors per month ",
       x = "",
       y = "")


# Daily number of tweets #
# NOT SURE: DOES THIS NEED TO BE GROUPED BY ACCOUNTS FIRST?
# SO AS TO SHOW VARIATION WITHIN GROUP?
daily <- tweets %>% 
  group_by(group, day) %>% 
  summarise(count = n()) %>% 
  mutate(benchmark = !str_detect(as.character(group), "EU "))
pl.output.daily <-
  ggplot(daily, aes(x = count, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  # coord_flip() +
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Average daily number of tweets",
       x= "",
       y= "")
  # + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

# Number of words per tweet #
pl.output.words <-
  ggplot(tweets, aes(x = ntoken, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  # coord_flip()+
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  # scale_y_discrete(limits = rev(levels(group)))+
  labs(title = "Average tweet length (words)",
       x= "",
       y= "")  # subtitle = "English language tweets only"
  # + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

# Combine output plots

# pl.output <- pl.output.month / (pl.output.daily + pl.output.words) + 
#   plot_annotation(title = "How much do supranational actors tweet?",
#                   theme = theme(plot.title = element_text(hjust = 0, 
#                                                           size = 14, face = "bold")))+
#   plot_layout(heights = c(2, 1))


pl.output <- pl.output.month + pl.output.daily  + 
  # plot_annotation(title = "How much do supranational actors tweet?",
  #                 theme = theme(plot.title = element_text(hjust = .5, 
  #                                                         size = 14, face = "bold")))+
  plot_layout(widths = c(2.5, 1))

ggsave("./plots/DescriptiveOverview/Output.png", plot = pl.output, width = 30, height = 12, units = "cm")




# Responsiveness ####

# Retweet shares
pl.retweets <-
  ggplot(tweets, aes(x = as.integer(is_retweet), y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  scale_x_continuous(labels = scales::label_percent(accuracy = 1L))+
  labs(title = "... re-tweet other users?",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold"))  
sum(tweets$is_retweet[tweets$tweetsample == "IO"])/nrow(tweets[tweets$tweetsample == "IO",]) # Sanity check

# Reply shares
pl.replies <-
  ggplot(tweets, aes(x = as.integer(is_reply), y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  scale_x_continuous(labels = label_percent(accuracy = 1L))+
  labs(title = "... reply to other users?",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold")) 

# Quote shares
pl.quotes <-
  ggplot(tweets, aes(x = as.integer(is_quote), y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  scale_x_continuous(labels = label_percent(accuracy = 1L))+
  labs(title = "... quote other users?",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold"))

# Combined responsiveness plot
pl.reponsiveness <- pl.retweets + pl.replies + pl.quotes +
  plot_annotation(title = "How many tweets ...",
                  theme = theme(plot.title = element_text(hjust = 0,
                                                          size = 14, face = "bold")))
ggsave("./plots/DescriptiveOverview/Responsiveness.png", plot = pl.reponsiveness, width = 30, height = 12, units = "cm")



# Responsiveness 2 ####
pl.mentions <-
  ggplot(tweets, aes(x = nmentions, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Users mentions (@) per tweet",
       x= "",
       y= "")
pl.hashtags <-
  ggplot(tweets, aes(x = nhashtags, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Hashtags (#) per tweet",
       x= "",
       y= "")
pl.reponsiveness2 <- pl.mentions + pl.hashtags
ggsave("./plots/DescriptiveOverview/Responsiveness2.png", plot = pl.reponsiveness2, width = 24, height = 10, units = "cm")



# Media usage ####
# in orignal (self-authored) tweets only

# Pictures
pl.photos <-
  ggplot(tweets[tweets$original, ], aes(x = as.integer(nphotos>0), y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  scale_x_continuous(labels = label_percent(accuracy = 1L))+
  labs(title = "Share of tweets with embedded picture",
       x= "",
       y= "")

# Videos
tweets$video <- (tweets$nvideos + tweets$ntube)>0 # Embeded and link-embedded videos
pl.videos <-
  ggplot(tweets[tweets$original, ], aes(x = as.integer(video), y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  scale_x_continuous(labels = label_percent(accuracy = 1L))+
  labs(title = "Share of tweets with embedded video",
       x= "",
       y= "")


# Emojis
pl.emojis <-
  ggplot(tweets[tweets$original, ], aes(x = emojicount, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Emojis / special symbols per tweet",
       x= "",
       y= "")

# External urls
pl.urls <-
  ggplot(tweets[tweets$original, ], aes(x = nexturl, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "External links per tweet",
       x= "",
       y= "")

# Combined Plot
pl.media <-
  (pl.photos+pl.videos) / (pl.emojis+pl.urls)+
  plot_annotation(caption = "Only original tweets (excluding re-tweets and quotes).")
ggsave("./plots/DescriptiveOverview/MediaUsage.png", plot = pl.media, width = 24, height = 20, units = "cm")



# Language ####

pl.flesch <-
  ggplot(tweets[tweets$original, ], aes(x = flesch, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Flesch/Kincaid reading ease score",
       x= "",
       y= "")

pl.familiarity <-
  ggplot(tweets[tweets$original, ], aes(x = familiarity, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Familiarity of vocabulary",
       x= "",
       y= "")

pl.verbal <-
  ggplot(tweets[tweets$original, ], aes(x = verbal, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Verb-to-noun ratio",
       x= "",
       y= "")

pl.sentiment <-
  ggplot(tweets[tweets$original, ], aes(x = lsd, y = group, color = benchmark, shape = benchmark)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = benchmarkcolors)+
  scale_shape_manual(values = benchmarkshapes)+
  labs(title = "Sentiment (LSD)",
       x= "",
       y= "")

# Combined plot
pl.language <-
  (pl.flesch + pl.familiarity) / (pl.verbal + pl.sentiment) +
  plot_annotation(caption = "Only original tweets (excluding re-tweets and quotes) with English-language content.")
  
ggsave("./plots/DescriptiveOverview/Language.png", plot = pl.language, width = 24, height = 20, units = "cm")







# Engagement ####
#################

# Hearts
pl.favs <-
  ggplot(df, aes(y = favorite_count, x = month, color = account_type, group = account_type))+
  # stat_summary(geom = "pointrange", fun.data = "mean_cl_boot") +
  stat_summary(geom = "line", fun = "mean", na.rm = T)+
  # geom_point()+
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_color_manual(values = accountcolors)+
  labs(title= "Average number of favorites per tweet and month",
       color = "",
       x= "", y = "")+
  theme(legend.position = c(0.2,.88),
        legend.background = element_blank())

# Retweets
pl.rets <- 
  ggplot(df, aes(y = retweet_count, x = month, color = account_type, group = account_type))+
  # stat_summary(geom = "pointrange", fun.data = "mean_cl_boot") +
  stat_summary(geom = "line", fun = "mean", na.rm = T)+
  # geom_point()+
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_color_manual(values = accountcolors)+
  labs(title= "Average number of retweets per tweet and month",
       color = "",
       x= "", y = "")    

# Combine
pl.engagement <-
  pl.favs/pl.rets +
  plot_annotation(title = "How much do users engage with tweets from supranational actors?",
                  caption = "Note that both favorite and retweet counts follow an extremely right-skewed distribution\nand are subject to strong individual outliers.",
                  theme = theme(plot.title = element_text(hjust = 0.5, 
                                                          size = 14, face = "bold")))

ggsave("./plots/DescriptiveOverview/Engagement.png", width = 20, height = 15, units = "cm")





# # Analyse daily tweet volume ####
# 
# # Daily number of tweets in sample
# days <- corpus %>% 
#   mutate(day = str_trim(str_extract(created_at, ".*^? "))) %>% 
#   select(day) %>% 
#   group_by(day) %>% 
#   summarise(count = n())
# 
# # Descriptives
# min(days$day)  
# max(days$day)
# mean(days$count)
# 
# # Time series
# dates <- seq(as.Date(min(days$day)), as.Date(max(days$day)), by = "days") %>% # all dates within range
#   as.data.frame() %>% 
#   rename(day = 1) %>% 
#   mutate(day = as.character(day))
# 
# dates <- left_join(dates, days, by = "day")
# dates$count[is.na(dates$count)] <- 0
# 
# breaks <- dates %>%  # Breaks for x-axis
#   filter(str_detect(day, "01-01$")) %>% # 1st January
#   select(day)
# breaks <- as.character(breaks[,1])
# labels <- str_remove(breaks, "-.*$") %>% unique() # Year only
# 
# ggplot(dates, aes(x= day, y= count)) + 
#   geom_col()+
#   scale_x_discrete(breaks = breaks, labels = labels)+
#   labs(title = "Daily volume of tweets in EUtweet sample",
#        subtitle = "117 verified accounts of supranational persons, offices, and institutions",
#        x = "\nDay",
#        y = "Number of tweets\n")+
#   theme_bw()+
#   theme()
# 
# ggsave("./plots/TweetVolumeDaily.png", width = 16, height = 10, units = "cm")
# 
# # Weekday
# old.setting <- Sys.getlocale("LC_TIME") # Store current time setting of locale
# Sys.setlocale("LC_TIME","English_United States.1252") # switch to English
# wdays <- dates %>% 
#   mutate(weekday = weekdays(as.Date(day))) %>% 
#   group_by(weekday) %>% 
#   summarise(mean = mean(count))
# Sys.setlocale("LC_TIME", old.setting) # Reinstate old LC Time setting
# wdays$weekday <- factor(wdays$weekday, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
# 
# ggplot(wdays, aes(x= mean, y= fct_rev(weekday))) + 
#   geom_col()+
#   labs(title = "Tweets per weekday in EUtweet sample",
#        subtitle = "117 verified accounts of supranational persons, offices, and institutions",
#        x = "\nAverage number of tweets\n(2009-03-13/2021-03-14) ",
#        y = "")+
#   theme_bw()+
#   theme()
# 
# ggsave("./plots/TweetVolumeWeekday.png", width = 16, height = 10, units = "cm")

