########################################################
# Project:    EU Tweet
# Task:       Analyse engagement with EU tweets
# Author:     Christian Rauh (01.06.2021)
########################################################


# Packages #####
library(tidyverse) # 1.3.0
library(patchwork) # 1.1.1
library(scales) # 1.1.1
library(margins)




# Prepare data ####

# As generated by 3_AnalyticDataSet.R and preceeding steps
# Keeping only the EU tweets
tweets <- read_rds("./data/AnalyticData_AllSamples.RDS") %>% 
  filter(str_detect(tweetsample, "EU "))

# Correct some coding nuissances
# Probably correct downstream!
tweets$nexturl[is.na(tweets$nexturl)] <- 0 # there were just none
tweets$nphotos[is.na(tweets$nphotos)] <- 0 # there were just none
tweets$nvideos[is.na(tweets$nvideos)] <- 0 # there were just none
tweets$ntube[is.na(tweets$ntube)] <- 0 # there were just none
tweets$lsd[!tweets$en_av] <- NA # If there was no english text, sentiment score is missing, not 0

# Mark original (self-authored) tweets
# excluding retweets and quotes
tweets$original <- tweets$is_retweet == F & tweets$is_quote == F

# Logical representations of media presence
tweets$video <- (tweets$nvideos + tweets$ntube) > 0 # Embeded and link-embedded videos
tweets$pic <- tweets$nphotos > 0
tweets$url <- tweets$nexturl > 0

# Personal accounts
tweets$personal <- str_detect(tweets$tweetsample, "pers. account")
sum(tweets$personal)

# Time markers
tweets$month <- str_extract(as.character(tweets$day), "[0-9]{4}-[0-9]{2}")



# Follower counts and normalisation of DVs ####

fcounts <- read_rds("./analysis_data/FollowerCountsInterpolated_EU.RDS") %>% 
  select(-follower_count) %>% 
  rename(day = date)

tweets <- tweets %>% left_join(fcounts, by = c("screen_name", "day"))
sum(is.na(tweets$follower_count_interpolated))

tweets$like_ratio <- tweets$like_count/tweets$follower_count_interpolated
tweets$retweet_ratio <- tweets$retweet_count/tweets$follower_count_interpolated
tweets$quote_ratio <- tweets$quote_count/tweets$follower_count_interpolated
tweets$reply_ratio <- tweets$reply_count/tweets$follower_count_interpolated



# Descriptive analysis of user engagement ####

# Probably this should happen in descriptive overview with benchmark samples
# Hard to interpret the absolute values

# ggplot params 
theme_set(theme_light() +
            theme(legend.position = "none",
                  axis.text = element_text(color = "black"),
                  plot.title = element_text(size=10, face = "bold"),
                  panel.grid.minor = element_blank(),
                  axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)))


# Plotting markers
t.breaks <- tweets %>% 
  filter(str_detect(month, "-01")) %>% # Only Januaries
  select(month) %>% 
  mutate(help = "help") %>% 
  unique() %>% 
  as.data.frame()
t.breaks <- t.breaks[ ,1]  # Atomic vector
t.labels <- str_remove(t.breaks, "-01")  


# Likes
pl.like_count <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = like_count, color = personal, group = personal)) +
  stat_summary(geom = "line", fun = "mean", ) +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of likes\nper supranational tweet and month",
       x = "",
       y = "",
       color = "Author account type:")+
  theme(legend.position = c(0.25,.85),
        legend.background = element_blank(),
        legend.text = element_text(size= 10),
        legend.title = element_text(size= 10))

pl.like_ratio <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = like_ratio, color = personal, group = personal)) +
  stat_smooth() +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_y_continuous(labels = scales::label_percent(accuracy = 0.01))+
  coord_cartesian(ylim = c(0,NA))+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of likes\nper supranational tweet\nas share of account followers",
       x = "",
       y = "",
       color = "Author account type:")+
  theme(legend.position = c(0.25,.85),
        legend.background = element_blank(),
        legend.text = element_text(size= 10),
        legend.title = element_text(size= 10))


# Retweets
pl.retweet_count <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = retweet_count, color = personal, group = personal)) +
  stat_summary(geom = "line", fun = "mean", ) +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of retweets\nper supranational tweet and month",
       x = "",
       y = "")

pl.retweet_ratio <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = retweet_ratio, color = personal, group = personal)) +
  stat_smooth() +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_y_continuous(labels = scales::label_percent(accuracy = 0.01))+
  coord_cartesian(ylim = c(0,NA))+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of retweets\nper supranational tweet\nas share of account followers",
       x = "",
       y = "")


# Quotes
pl.quote_count <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = quote_count, color = personal, group = personal)) +
  stat_summary(geom = "line", fun = "mean", ) +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of quotes\nper supranational tweet and month",
       x = "",
       y = "")

pl.quote_ratio <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = quote_ratio, color = personal, group = personal)) +
  stat_smooth() +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_y_continuous(labels = scales::label_percent(accuracy = 0.01))+
  coord_cartesian(ylim = c(0,NA))+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of quotes\nper supranational tweet\nas share of account followers",
       x = "",
       y = "")


# Replies
pl.reply_count <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = reply_count, color = personal, group = personal)) +
  stat_summary(geom = "line", fun = "mean", ) +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of replies\nper supranational tweet and month",
       x = "",
       y = "")

pl.reply_ratio <-
  ggplot(tweets[tweets$original, ], aes(x = month, y = reply_ratio, color = personal, group = personal)) +
  stat_smooth() +
  scale_x_discrete(breaks = t.breaks, labels = t.labels)+
  scale_y_continuous(labels = scales::label_percent(accuracy = 0.01))+
  coord_cartesian(ylim = c(0,NA))+
  scale_colour_manual(values = c("#003399", "#1da1f2"), labels = c("institutional", "personal")) +
  labs(title = "Average number of replies\nper supranational tweet\nas share of account followers",
       x = "",
       y = "")

# Combined plots
pl.engagement_count <-
  (pl.like_count+pl.retweet_count)/
  (pl.quote_count+pl.reply_count)
ggsave("./plots/UserEngagement/UserEngagementOverTimeAbsolute.png", plot = pl.engagement_count, width = 20, height = 20, units = "cm")

pl.engagement_ratio <-
  (pl.like_ratio+pl.retweet_ratio)/
  (pl.quote_ratio+pl.reply_ratio)
ggsave("./plots/UserEngagement/UserEngagementOverTimeRatio.png", plot = pl.engagement_ratio, width = 20, height = 20, units = "cm")






# Regression model data ####

df <- tweets %>% 
  filter(original) %>% # Only self-authored tweets
  select(id, screen_name, day, # ID markers for residual analysis
         like_count, retweet_count, quote_count, reply_count, # DVs: engagement rates
         emojicount, pic, video, url, # IVs: Media
         nmentions, nhashtags, # IVs: Responsiveness
         flesch, familiarity, verbal, lsd, # IVs: Language 
         personal) %>% # IV: Personal account
  filter(complete.cases(.)) # Keep only complete cases, mainly drops tweets without english content


