###############################################################
# Project:    EU Tweet
# Task:       Analyse interactivity (responsiveness) patterns
# Author:     Christian Rauh (29.06.2021)
##############################################################

# Packages ####
library(tidyverse) # 1.3.0
library(patchwork) # 1.1.1
library(ggridges) # 0.5.2
library(ggtext) # 0.1.1
library(scales) # 1.1.1
library(stargazer) # 5.2.2


# Prepare the data ####

# As generated by 3_AnalyticDataSet.R and preceeding steps
tweets <- read_rds("./data/AnalyticData_AllSamples.RDS")

# Filter some accounts
tweets <- tweets %>% 
  filter(screen_name != "HMRCcustomers") %>%  # Customer support account
  filter(screen_name != "DVLAgovuk") %>%      # Online service account of the Driver&Vehicle licensing agency
  filter(screen_name != "nsandihelp")         # A help desk (what is this org anyway?)


# Add personal institutional distinction for the IO sample
# Coding by CR and KBH consistent
iopersonal <- read.csv2("./analysis_data/IO_account_coding_CR.csv") %>% 
  filter(personal == 1) 
iopersonal <- iopersonal[,1] # Screen names to atomic vector
tweets$tweetsample[tweets$screen_name %in% iopersonal] <- "IO (pers. account)"
tweets$tweetsample[tweets$tweetsample == "IO"] <- "IO (inst. account)"
rm(iopersonal)

# Clean group variables (for plotting)
tweets$group1 <- tweets$tweetsample %>% 
  str_replace(" ", "\n") %>% ## Add line breaks
  factor(levels = c("EU\n(inst. account)", # Order as factor
                    "EU\n(pers. account)",
                    "UK\n(inst. account)",
                    "UK\n(pers. account)",
                    "IO\n(inst. account)",
                    "IO\n(pers. account)",
                    "Random\nTweets")) %>% 
  fct_rev() # Reverse, so that EU always comes out on top (for horizontal plots, reverse in ggplot call)

tweets$group2 <- tweets$tweetsample %>% 
  str_remove(" .*$") %>% # Remove pers/inst distinction (for color coding later)
  factor(levels = c("EU", # Order as factor
                    "UK",
                    "IO",
                    "Random")) %>% 
  fct_rev() # Reverse, so that EU alsways comes out on top

# Mark group of benchmark samples separately
tweets$benchmark <- !str_detect(tweets$tweetsample, "EU ")

# Retain copy of screen_names / sample assocs
# for easy labelling aggregated data downstream
account.types <- tweets %>% 
  select(screen_name, group1, group2, benchmark) %>% 
  unique()
account.types <- account.types %>% 
  filter(!(screen_name == "BaldwinMatthew_" & group2 == "Random")) # Crazy coincidence!
sum(duplicated(account.types$screen_name))

# Correct some coding nuissances
# Probably correct downstream!
tweets$nexturl[is.na(tweets$nexturl)] <- 0 # there were just none
tweets$nphotos[is.na(tweets$nphotos)] <- 0 # there were just none
tweets$nvideos[is.na(tweets$nvideos)] <- 0 # there were just none
tweets$ntube[is.na(tweets$ntube)] <- 0 # there were just none
tweets$lsd[!tweets$en_av] <- NA # If there was no english text, sentiment score is missing, not 0

# Mark original (self-authored) tweets
# excluding retweets and quotes
tweets$original <- tweets$is_retweet == F & tweets$is_quote == F
sum(tweets$original)

# Time markers
tweets$month <- str_extract(as.character(tweets$day), "[0-9]{4}-[0-9]{2}")


# Sample for testing purpose
# tweets <- tweets %>% sample_n(10000)


# Overarching ggplot params ####

theme_set(theme_light() +
            theme(legend.position = "none",
                  axis.text = element_text(color = "black"),
                  plot.title = element_text(size=10),
                  panel.grid.minor = element_blank()))

benchmarkcolors <- c("#003399", "#FFCC00") # EU, all the way down ...
benchmarkshapes <- c(18, 19)




# Responsiveness ####

# Example share for comp
# sum(tweets$is_retweet[tweets$tweetsample == "IO"])/nrow(tweets[tweets$tweetsample == "IO",]) # Sanity check


# Retweet shares
pl.retweets <-
  ggplot(tweets, aes(x = as.integer(is_retweet), y = group1, color = group2)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = c("grey30", "#FFCC00", "darkred", "#003399"))+
  scale_x_continuous(labels = scales::label_percent(accuracy = 1L))+
  facet_wrap(.~ reorder(group2, desc(group2)), scales = "free_y", ncol = 1, strip.position = "right")+
  labs(title = "Retweets",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold"))  

# Reply shares
pl.replies <-
  ggplot(tweets, aes(x = as.integer(is_reply), y = group1, color = group2)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = c("grey30", "#FFCC00", "darkred", "#003399"))+
  scale_x_continuous(labels = label_percent(accuracy = 1L))+
  facet_wrap(.~ reorder(group2, desc(group2)), scales = "free_y", ncol = 1, strip.position = "right")+
  labs(title = "Replies",
       x= "\nShare of overall tweets",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold")) 

# Quote shares
pl.quotes <-
  ggplot(tweets, aes(x = as.integer(is_quote), y = group1, color = group2)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = c("grey30", "#FFCC00", "darkred", "#003399"))+
  scale_x_continuous(labels = label_percent(accuracy = 1L))+
  facet_wrap(.~ reorder(group2, desc(group2)), scales = "free_y", ncol = 1, strip.position = "right")+
  labs(title = "Quotes",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold"))

# Combined responsiveness plot
pl.reponsiveness <- pl.retweets + pl.replies + pl.quotes 
# + plot_annotation(title = "How many tweets ...",
#                 theme = theme(plot.title = element_text(hjust = 0,
#                                                         size = 14, face = "bold")))
ggsave("./plots/DescriptiveOverview/InteractivityShares.png", plot = pl.reponsiveness, width = 30, height = 12, units = "cm")


# Responsiveness 2 ####

# CHECK HOW INF VALUES ARE HANDLED HERE!

pl.mentions <-
  ggplot(tweets, aes(x = nmentions, y = group1, color = group2)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = c("grey30", "#FFCC00", "darkred", "#003399"))+
  facet_wrap(.~ reorder(group2, desc(group2)), scales = "free_y", ncol = 1, strip.position = "right")+
  labs(title = "Users mentions (@) per tweet",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold"))
pl.hashtags <-
  ggplot(tweets, aes(x = nhashtags, y = group1, color = group2)) +
  stat_summary(geom = "pointrange", fun.data = "mean_cl_boot", size = .7) + 
  scale_color_manual(values = c("grey30", "#FFCC00", "darkred", "#003399"))+
  facet_wrap(.~ reorder(group2, desc(group2)), scales = "free_y", ncol = 1, strip.position = "right")+
  labs(title = "Hashtags (#) per tweet",
       x= "",
       y= "")+
  theme(plot.title = element_text(hjust = .5, face = "bold"))

pl.reponsiveness2 <- pl.mentions + pl.hashtags
ggsave("./plots/DescriptiveOverview/InteractivityMentionsHashtags.png", plot = pl.reponsiveness2, width = 24, height = 10, units = "cm")




# IDEAS:
# 1. Stacked area chart for EU over time, next to stacked bar by actor category (2:1)
# 2. Concentration indices (Hirschmann) for retweeted, replied,a nd quoted user ids - plurality vs bubble (do we have the data?)


